In [142]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [143]:
df = pd.read_csv('/content/breast-cancer.csv')
df.sample(4)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
443,909777,B,10.57,18.32,66.82,340.9,0.08142,0.04462,0.01993,0.01111,...,10.94,23.31,69.35,366.3,0.09794,0.06542,0.03986,0.02222,0.2699,0.06736
433,908445,M,18.82,21.97,123.70,1110.0,0.10180,0.13890,0.15940,0.08744,...,22.66,30.93,145.30,1603.0,0.13900,0.34630,0.39120,0.17080,0.3007,0.08314
219,88119002,M,19.53,32.47,128.00,1223.0,0.08420,0.11300,0.11450,0.06637,...,27.90,45.41,180.20,2477.0,0.14080,0.40970,0.39950,0.16250,0.2713,0.07568
343,898431,M,19.68,21.68,129.90,1194.0,0.09797,0.13390,0.18630,0.11030,...,22.75,34.66,157.60,1540.0,0.12180,0.34580,0.47340,0.22550,0.4045,0.07918

In [144]:
df.drop('id', axis=1, inplace=True)
df.shape

(569, 31)

In [145]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

**Train Test split**

In [146]:
X_train,X_test,y_train,y_test = train_test_split(df.drop('diagnosis', axis=1), df['diagnosis'], test_size=0.2, random_state=42)

**Scaling**

In [147]:
Scaler = StandardScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)

**Label Encoder**

We have to encode the categorical columns using LableEncoder()

In [148]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [149]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])

**Numpy arrays to Pytorch tensors**

In [150]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [151]:
X_train_tensor.shape

torch.Size([455, 30])

In [152]:
y_train_tensor.shape

torch.Size([455])

**Defining the model**

In [153]:
import torch.nn as nn

In [154]:
class MySimpleNN(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,num_features):
    out = self.linear(num_features)
    out = self.sigmoid(out)
    return out

# Built-in (Loss Funtion)
# def loss_function(self,y_pred,y_true):
#   Loss = nn.BCELoss()
#   return Loss(y_pred,y_true)

In [155]:
loss_function = nn.BCELoss()

# **Some Important Parameters**

**Learning Rate (lr = 0.1)**

The learning rate determines how much the model updates its weights after each optimization step.

**Mathematically**, after backpropagation computes the gradients, the optimizer updates the weights as:

**New Weight=Old Weight−(Learning Rate×Gradient)**

If:

**Learning Rate = 0.1**

the optimizer takes relatively large steps toward minimizing the loss.

**Number of Epochs (epochs = 25)**

An epoch means one complete pass of the entire training dataset through the model.

In [156]:
learning_rate = 0.1
epochs = 25

# **Training Pipeline**

In [157]:
model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)

for epoch in range(epochs):

    # Forward pass
    y_pred = model(X_train_tensor)

    # Calculate loss
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))

    # clear gradients before backward pass good technique
    optimizer.zero_grad()

    # Backward pass
    loss.backward()

    #update parameters
    optimizer.step()

    # Print loss
    print(f"Epoch {epoch+1}: Loss = {loss.item()}")

Epoch 1: Loss = 0.7086566686630249
Epoch 2: Loss = 0.5291653275489807
Epoch 3: Loss = 0.4359869956970215
Epoch 4: Loss = 0.3792763948440552
Epoch 5: Loss = 0.34074023365974426
Epoch 6: Loss = 0.31260940432548523
Epoch 7: Loss = 0.2910160422325134
Epoch 8: Loss = 0.2738131582736969
Epoch 9: Loss = 0.2597113847732544
Epoch 10: Loss = 0.24788841605186462
Epoch 11: Loss = 0.2377944141626358
Epoch 12: Loss = 0.2290470004081726
Epoch 13: Loss = 0.22137179970741272
Epoch 14: Loss = 0.2145664095878601
Epoch 15: Loss = 0.20847788453102112
Epoch 16: Loss = 0.20298855006694794
Epoch 17: Loss = 0.19800598919391632
Epoch 18: Loss = 0.19345667958259583
Epoch 19: Loss = 0.18928121030330658
Epoch 20: Loss = 0.18543100357055664
Epoch 21: Loss = 0.18186594545841217
Epoch 22: Loss = 0.1785525530576706
Epoch 23: Loss = 0.1754625290632248
Epoch 24: Loss = 0.17257191240787506
Epoch 25: Loss = 0.16986019909381866

In [158]:
model.linear.weight # Now these weights have less error

Parameter containing:
tensor([[ 0.1770,  0.1223,  0.3376,  0.3332,  0.0468,  0.0292,  0.3829,  0.4185,
         -0.0332,  0.0046,  0.1410,  0.0634,  0.2526,  0.1431, -0.1002, -0.0697,
         -0.0873, -0.0534,  0.0601, -0.0628,  0.1841,  0.2497,  0.0926,  0.2682,
          0.2677,  0.1329,  0.0650,  0.3431,  0.2557,  0.0923]],
       requires_grad=True)

In [159]:
model.linear.bias

Parameter containing:
tensor([-0.1327], requires_grad=True)

# **Evaluation**

here we are doing the evaluation not the  backpropagation so we don't need gradients

In [160]:
#model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Test accuracy: {accuracy}')

Test accuracy: 0.5280086398124695